source 'https://rubygems.org'

gem 'rails', '4.2.0'
gem 'backbone-on-rails'
gem 'bcrypt'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'bootstrap-sass'
gem 'newrelic_rpm'

group :development, :test do
  gem 'annotate'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'byebug'
  gem 'pry-rails'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end
