source 'https://rubygems.org'

gem 'backbone-on-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '4.1.7'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

gem 'kaminari'
gem 'friendly_id'
gem 'delayed_job_active_record'

group :development do
  gem 'letter_opener'
end

group :development, :test do
  gem 'better_errors'
  gem 'binding_of_caller'
end

gem 'rspec-rails', group: :test
